#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../../.."

if ! command -v wasm-pack >/dev/null 2>&1; then
  echo "wasm-pack is required for this example. Install with: cargo install wasm-pack --locked, or run ./scripts/setup-dev-env.sh" >&2
  exit 1
fi

# HYDRA's browser handshake path performs ML-KEM + ML-DSA work. Some browsers
# trap with the wasm-ld default stack during that path, so build the web package
# with an explicit stack. Apps may override this, but should not lower it without
# rerunning the browser persistence/handshake probes.
HYDRA_WASM_STACK_SIZE="${HYDRA_WASM_STACK_SIZE:-16777216}"
HYDRA_PREVIOUS_RUSTFLAGS="${RUSTFLAGS:-}"
export RUSTFLAGS="${HYDRA_PREVIOUS_RUSTFLAGS} -C link-arg=-zstack-size=${HYDRA_WASM_STACK_SIZE}"

out_dir="examples/webrtc_manual_carrier/web/pkg"
rm -rf "$out_dir"
wasm-pack build crates/hydra-msg-wasm --target web --release --out-dir ../../examples/webrtc_manual_carrier/web/pkg
cat > "$out_dir/README.md" <<'EOF_README'
# HYDRA WebRTC manual carrier generated WASM package

This directory is generated by `examples/webrtc_manual_carrier/scripts/build-wasm.sh`.

It is example-local output for the WebRTC manual carrier page. Do not edit generated files here directly; rebuild from the repo root instead.

Useful repo docs:

- [WebRTC manual carrier example](../../README.md)
- [Main README](../../../../README.md)
- [Public developer API](../../../../docs/spec/public-developer-api.md)
- [Browser/WASM bindings](../../../../docs/impl/wasm-javascript-bindings.md)
EOF_README
echo "Built WebRTC manual carrier example-local WASM package: examples/webrtc_manual_carrier/web/pkg"
