pub(super) const TEMPLATE_TEXT: [&str; 32] = [
    "{opener}, we could {manner} {action} our {topic} by the {place}; {connector}, it felt {tone}.",
    "{opener}, by the {place}, we chose to {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, near the {place}, we could {manner} {action} our {topic}; {connector}, things felt {tone}.",
    "{opener}, at the {place}, we chose to {manner} {action} our {topic}; {connector}, all seemed {tone}.",
    "{opener}, we met near the {place} to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, we paused by the {place} to {manner} {action} our {topic}; {connector}, it stayed {tone}.",
    "{opener}, at the {place}, we had time to {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, the {topic} arose near the {place}, so we chose to {manner} {action} it; {connector}, it felt {tone}.",
    "{opener}, while near the {place}, we could {manner} {action} our {topic}; {connector}, it remained {tone}.",
    "{opener}, after reaching the {place}, we chose to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, with the {place} nearby, we could {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, during our stop at the {place}, we chose to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, before leaving the {place}, we chose to {manner} {action} our {topic}; {connector}, all felt {tone}.",
    "{opener}, once at the {place}, we could {manner} {action} our {topic}; {connector}, things seemed {tone}.",
    "{opener}, we found time by the {place} to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, the {place} gave us time to {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, a pause near the {place} helped us {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, our walk to the {place} let us {manner} {action} our {topic}; {connector}, it stayed {tone}.",
    "{opener}, over coffee by the {place}, we chose to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, in a quiet spot by the {place}, we could {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, on the way to the {place}, we chose to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, we stopped at the {place} to {manner} {action} our {topic}; {connector}, it remained {tone}.",
    "{opener}, after a walk to the {place}, we chose to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, we sat near the {place} to {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, we spoke by the {place} to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, our visit to the {place} let us {manner} {action} our {topic}; {connector}, it stayed {tone}.",
    "{opener}, our stop at the {place} made it easy to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, while passing the {place}, we could {manner} {action} our {topic}; {connector}, it seemed {tone}.",
    "{opener}, with time near the {place}, we chose to {manner} {action} our {topic}; {connector}, all felt {tone}.",
    "{opener}, we took a moment at the {place} to {manner} {action} our {topic}; {connector}, it felt {tone}.",
    "{opener}, around the {place}, we could {manner} {action} our {topic}; {connector}, things stayed {tone}.",
    "{opener}, beside the {place}, we chose to {manner} {action} our {topic}; {connector}, it remained {tone}.",
];

pub(super) const OPENERS: [&str; 32] = [
    "Earlier",
    "Later",
    "Recently",
    "Yesterday",
    "Today",
    "Tonight",
    "Initially",
    "Eventually",
    "Afterward",
    "Meanwhile",
    "Sometimes",
    "Usually",
    "Fortunately",
    "Naturally",
    "Gradually",
    "Briefly",
    "Soon",
    "Beforehand",
    "Afterwards",
    "Lately",
    "Once",
    "First",
    "Next",
    "Finally",
    "Often",
    "Rarely",
    "Normally",
    "Thankfully",
    "Honestly",
    "Personally",
    "Perhaps",
    "Anyway",
];

pub(super) const MANNERS: [&str; 32] = [
    "carefully",
    "casually",
    "briefly",
    "quietly",
    "slowly",
    "warmly",
    "openly",
    "patiently",
    "calmly",
    "thoughtfully",
    "privately",
    "honestly",
    "simply",
    "kindly",
    "eagerly",
    "deliberately",
    "readily",
    "gently",
    "directly",
    "clearly",
    "quickly",
    "freely",
    "sincerely",
    "seriously",
    "reasonably",
    "thoroughly",
    "politely",
    "smoothly",
    "willingly",
    "closely",
    "actively",
    "properly",
];

pub(super) const ACTIONS: [&str; 32] = [
    "discuss",
    "review",
    "consider",
    "adjust",
    "confirm",
    "note",
    "plan",
    "describe",
    "compare",
    "revisit",
    "organize",
    "check",
    "remember",
    "mention",
    "explore",
    "arrange",
    "outline",
    "assess",
    "refine",
    "explain",
    "settle",
    "coordinate",
    "summarize",
    "evaluate",
    "clarify",
    "examine",
    "resolve",
    "prepare",
    "share",
    "address",
    "finalize",
    "simplify",
];

pub(super) const TOPICS: [&str; 32] = [
    "schedule",
    "route",
    "meeting",
    "plan",
    "idea",
    "timing",
    "details",
    "destination",
    "options",
    "notes",
    "question",
    "update",
    "arrangement",
    "invitation",
    "proposal",
    "reservation",
    "commute",
    "venue",
    "calendar",
    "lunch",
    "coffee",
    "trip",
    "message",
    "choice",
    "reminder",
    "request",
    "event",
    "booking",
    "visit",
    "task",
    "concern",
    "decision",
];

pub(super) const PLACES: [&str; 32] = [
    "station",
    "cafe",
    "library",
    "garden",
    "office",
    "market",
    "hotel",
    "museum",
    "restaurant",
    "theater",
    "park",
    "harbor",
    "campus",
    "bookstore",
    "square",
    "entrance",
    "plaza",
    "bridge",
    "gallery",
    "lobby",
    "terrace",
    "bakery",
    "corner",
    "courtyard",
    "lounge",
    "center",
    "trail",
    "depot",
    "fountain",
    "pier",
    "avenue",
    "patio",
];

pub(super) const CONNECTORS: [&str; 32] = [
    "afterward",
    "meanwhile",
    "eventually",
    "naturally",
    "fortunately",
    "later",
    "then",
    "ultimately",
    "overall",
    "instead",
    "similarly",
    "still",
    "finally",
    "otherwise",
    "somehow",
    "thankfully",
    "additionally",
    "however",
    "therefore",
    "perhaps",
    "consequently",
    "admittedly",
    "certainly",
    "clearly",
    "indeed",
    "nevertheless",
    "separately",
    "soon",
    "notably",
    "personally",
    "honestly",
    "interestingly",
];

pub(super) const TONES: [&str; 32] = [
    "calm",
    "comfortable",
    "constructive",
    "easy",
    "familiar",
    "friendly",
    "honest",
    "natural",
    "peaceful",
    "positive",
    "practical",
    "private",
    "productive",
    "relaxed",
    "reassuring",
    "worthwhile",
    "clear",
    "settled",
    "sensible",
    "balanced",
    "complete",
    "encouraging",
    "useful",
    "steady",
    "open",
    "warm",
    "manageable",
    "promising",
    "direct",
    "sincere",
    "smooth",
    "welcome",
];
