param(
    [Parameter(Mandatory = $true)] [string] $Version
)

$ErrorActionPreference = "Stop"
if ($Version -notmatch '^v\d+\.\d+\.\d+($|-.*$)') {
    throw "usage: .\scripts\release\create-release-package.ps1 vX.Y.Z"
}

$RepoRoot = (git rev-parse --show-toplevel).Trim()
Set-Location $RepoRoot

if ($env:HYDRA_RELEASE_ALLOW_DIRTY -ne "1") {
    $dirty = git status --porcelain
    if ($dirty) {
        throw "refusing to create release package from a dirty working tree; commit changes first or set HYDRA_RELEASE_ALLOW_DIRTY=1 for a local dry run"
    }
}

foreach ($cmd in @("cargo", "git", "python3")) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        throw "missing required release tool: $cmd"
    }
}

$Commit = (git rev-parse HEAD).Trim()
$SourceEpoch = (git log -1 --format=%ct HEAD).Trim()
$env:SOURCE_DATE_EPOCH = $SourceEpoch
$ReleaseDir = Join-Path "release-artifacts" $Version
if (Test-Path $ReleaseDir) { Remove-Item -Recurse -Force $ReleaseDir }
New-Item -ItemType Directory -Force -Path "$ReleaseDir/sbom", "$ReleaseDir/crates", "$ReleaseDir/logs" | Out-Null

Write-Host "==> release package: $Version"
Write-Host "==> commit: $Commit"

$Prefix = "hydra-msg-$($Version.TrimStart('v'))/"
$TarPath = "$ReleaseDir/hydra-msg-$Version-source.tar"
$GzPath = "$ReleaseDir/hydra-msg-$Version-source.tar.gz"
git archive --format=tar --prefix=$Prefix HEAD --output=$TarPath
# PowerShell fallback: gzip includes timestamp metadata, so Unix users should prefer .sh for byte-for-byte gzip reproducibility.
# The tar stream itself is generated by git from the selected commit.
if (Test-Path $GzPath) { Remove-Item $GzPath }
$in = [System.IO.File]::OpenRead((Resolve-Path $TarPath))
$out = [System.IO.File]::Create((Join-Path (Get-Location) $GzPath))
try {
    $gzip = New-Object System.IO.Compression.GzipStream($out, [System.IO.Compression.CompressionLevel]::Optimal)
    try { $in.CopyTo($gzip) } finally { $gzip.Dispose() }
} finally { $in.Dispose(); $out.Dispose() }
Remove-Item $TarPath

Write-Host "==> cargo package maintained crates"
Set-Content -Encoding utf8 "$ReleaseDir/logs/cargo-package.log" ""
Get-ChildItem crates/*/Cargo.toml | ForEach-Object {
    Add-Content "$ReleaseDir/logs/cargo-package.log" "==> cargo package --manifest-path $($_.FullName)"
    cargo package --manifest-path $_.FullName --locked --allow-dirty *>> "$ReleaseDir/logs/cargo-package.log"
}
Get-ChildItem target/package -Filter *.crate | Copy-Item -Destination "$ReleaseDir/crates"

Write-Host "==> generate SBOM"
python3 scripts/release/generate-sbom.py --repo . --version $Version --output "$ReleaseDir/sbom/hydra-msg-$Version-cyclonedx.json"
cargo metadata --locked --format-version 1 | Out-File -Encoding utf8 "$ReleaseDir/sbom/hydra-msg-$Version-cargo-metadata.json"

@"
HYDRA-MSG release manifest
version: $Version
git_commit: $Commit
source_date_epoch: $SourceEpoch
repository: https://github.com/peavey2787/hydra-msg
msrv: 1.88
license: GPL-2.0-or-later
security_policy: SECURITY.md
private_vulnerability_reporting: https://github.com/peavey2787/hydra-msg/security/advisories/new
"@ | Set-Content -Encoding utf8 "$ReleaseDir/RELEASE-MANIFEST.txt"

Write-Host "==> hash artifacts"
Push-Location $ReleaseDir
Get-ChildItem -Recurse -File |
    Where-Object { $_.Name -notin @("SHA256SUMS.txt", "SHA256SUMS.txt.asc") -and $_.Extension -ne ".asc" } |
    Sort-Object FullName |
    ForEach-Object {
        $relative = Resolve-Path -Relative $_.FullName
        $relative = $relative.TrimStart('.', '\', '/') -replace '\\','/'
        "$((Get-FileHash -Algorithm SHA256 $_.FullName).Hash.ToLower())  $relative"
    } | Set-Content -Encoding ascii SHA256SUMS.txt
Pop-Location

Write-Host "Release package created: $ReleaseDir"
Write-Host "Next: .\scripts\release\sign-release-artifacts.ps1 $Version [gpg-key-id]"
