[package]
name = "hydra-msg-example-stego-lan-chat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
hydra-stego = { version = "0.1.0", path = "../../crates/hydra-stego" }

[lints]
workspace = true
