pub(in crate::deterministic) const BUILD_STATES: [&str; 16] = [
    "SUCCESS",
    "READY",
    "RUNNING",
    "QUEUED",
    "PASS",
    "COMPLETE",
    "VERIFIED",
    "CLEAN",
    "CACHE HIT",
    "TESTS PASS",
    "BUILD percent COMPLETE",
    "ARTIFACT READY",
    "INPUTS LOCKED",
    "OUTPUT VERIFIED",
    "EXIT CODE ZERO",
    "RETRY PENDING",
];

pub(in crate::deterministic) const METRIC_STATES: [&str; 16] = [
    "NOMINAL",
    "STEADY",
    "RISING",
    "FALLING",
    "ACTIVE",
    "IDLE",
    "SATURATED",
    "AVAILABLE",
    "WITHIN RANGE",
    "BELOW LIMIT",
    "ABOVE BASELINE",
    "SAMPLE READY",
    "WINDOW COMPLETE",
    "SCRAPE SUCCESS",
    "EXPORT READY",
    "COLLECTION ACTIVE",
];

pub(in crate::deterministic) const DEPLOY_STATES: [&str; 16] = [
    "STAGED",
    "READY",
    "ROLLING OUT",
    "ACTIVE",
    "HEALTHY",
    "DRAINING",
    "PROMOTED",
    "COMPLETE",
    "ROLLBACK READY",
    "CANARY HEALTHY",
    "TRAFFIC SHIFTED",
    "DEPLOY percent COMPLETE",
    "MANIFEST VERIFIED",
    "TARGET READY",
    "RELEASE STAGED",
    "GATE PASS",
];

pub(in crate::deterministic) const TRACE_RESULTS: [&str; 16] = [
    "PASS",
    "WARN",
    "FAIL",
    "RETRY",
    "TIMEOUT",
    "MISMATCH",
    "INVALID",
    "BLOCKED",
    "DEGRADED",
    "RECOVERED",
    "CHECKSUM FAIL",
    "SIGNATURE VALID",
    "POLICY REJECT",
    "DEPENDENCY MISSING",
    "RETRY PENDING",
    "ERROR CONFIRMED",
];
