pub(in crate::deterministic) const BUILD_ACTIONS: [&str; 16] = [
    "queue", "schedule", "compile", "test", "package", "link", "verify", "upload", "sign", "cache",
    "restore", "publish", "promote", "merge", "checkout", "build",
];

pub(in crate::deterministic) const METRIC_ACTIONS: [&str; 16] = [
    "sample",
    "measure",
    "observe",
    "count",
    "aggregate",
    "export",
    "scrape",
    "record",
    "poll",
    "probe",
    "track",
    "gauge",
    "summarize",
    "flush",
    "rotate",
    "emit",
];

pub(in crate::deterministic) const DEPLOY_ACTIONS: [&str; 16] = [
    "stage",
    "deploy",
    "rollout",
    "promote",
    "activate",
    "restart",
    "drain",
    "route",
    "sync",
    "replicate",
    "reconcile",
    "switch",
    "rollback",
    "release",
    "publish",
    "verify",
];

pub(in crate::deterministic) const TRACE_ACTIONS: [&str; 16] = [
    "inspect",
    "validate",
    "audit",
    "trace",
    "retry",
    "reject",
    "quarantine",
    "compare",
    "hash",
    "scan",
    "diagnose",
    "isolate",
    "report",
    "capture",
    "verify",
    "classify",
];

pub(in crate::deterministic) const BUILD_QUALIFIERS: [&str; 16] = [
    "current",
    "candidate",
    "integration",
    "release",
    "debug",
    "production",
    "signed",
    "cached",
    "primary",
    "secondary",
    "staged",
    "pending",
    "verified",
    "incremental",
    "nightly",
    "clean",
];

pub(in crate::deterministic) const METRIC_QUALIFIERS: [&str; 16] = [
    "service",
    "runner",
    "pipeline",
    "cache",
    "queue",
    "network",
    "build",
    "artifact",
    "worker",
    "node",
    "deploy",
    "registry",
    "storage",
    "process",
    "system",
    "validation",
];

pub(in crate::deterministic) const DEPLOY_QUALIFIERS: [&str; 16] = [
    "primary",
    "canary",
    "blue",
    "green",
    "staged",
    "candidate",
    "production",
    "regional",
    "rolling",
    "active",
    "backup",
    "signed",
    "verified",
    "current",
    "next",
    "stable",
];

pub(in crate::deterministic) const TRACE_QUALIFIERS: [&str; 16] = [
    "current",
    "failed",
    "pending",
    "retried",
    "blocked",
    "invalid",
    "stale",
    "remote",
    "local",
    "signed",
    "cached",
    "runtime",
    "policy",
    "dependency",
    "network",
    "storage",
];

pub(in crate::deterministic) const BUILD_TOPICS: [&str; 16] = [
    "PR",
    "build",
    "branch",
    "job",
    "artifact",
    "target",
    "package",
    "pipeline",
    "test",
    "commit",
    "bundle",
    "image",
    "binary",
    "workspace",
    "lockfile",
    "manifest",
];

pub(in crate::deterministic) const METRIC_TOPICS: [&str; 16] = [
    "latency",
    "throughput",
    "utilization",
    "depth",
    "hit rate",
    "error rate",
    "coverage",
    "duration",
    "capacity",
    "backlog",
    "memory",
    "cpu",
    "bandwidth",
    "retries",
    "availability",
    "saturation",
];

pub(in crate::deterministic) const DEPLOY_TOPICS: [&str; 16] = [
    "service",
    "release",
    "image",
    "deployment",
    "replica",
    "node",
    "cluster",
    "route",
    "revision",
    "manifest",
    "artifact",
    "target",
    "gateway",
    "worker",
    "instance",
    "rollout",
];

pub(in crate::deterministic) const TRACE_TOPICS: [&str; 16] = [
    "check",
    "error",
    "incident",
    "request",
    "response",
    "digest",
    "signature",
    "policy",
    "dependency",
    "timeout",
    "retry",
    "probe",
    "trace",
    "event",
    "record",
    "failure",
];

pub(in crate::deterministic) const BUILD_CONTEXTS: [&str; 16] = [
    "build runner",
    "compile worker",
    "test shard",
    "package worker",
    "artifact store",
    "integration runner",
    "release runner",
    "cache node",
    "source worker",
    "link worker",
    "build node",
    "test runner",
    "package node",
    "signing worker",
    "upload worker",
    "pipeline runner",
];

pub(in crate::deterministic) const METRIC_CONTEXTS: [&str; 16] = [
    "metrics endpoint",
    "telemetry pipeline",
    "service probe",
    "runner telemetry",
    "pipeline telemetry",
    "cache metrics",
    "queue telemetry",
    "node metrics",
    "system metrics",
    "process metrics",
    "network metrics",
    "storage metrics",
    "registry metrics",
    "worker telemetry",
    "validation metrics",
    "deploy telemetry",
];

pub(in crate::deterministic) const DEPLOY_CONTEXTS: [&str; 16] = [
    "deploy controller",
    "release runner",
    "service node",
    "rollout controller",
    "traffic controller",
    "cluster node",
    "canary runner",
    "replica controller",
    "gateway node",
    "release controller",
    "deploy worker",
    "route controller",
    "manifest worker",
    "target node",
    "instance worker",
    "production runner",
];

pub(in crate::deterministic) const TRACE_CONTEXTS: [&str; 16] = [
    "validation worker",
    "diagnostic agent",
    "error monitor",
    "policy worker",
    "dependency checker",
    "network probe",
    "storage checker",
    "signature worker",
    "checksum worker",
    "runtime agent",
    "request monitor",
    "response monitor",
    "retry worker",
    "trace agent",
    "incident worker",
    "audit worker",
];

pub(in crate::deterministic) const EVIDENCE_RESTRICTIONS: [&str; 16] = [
    "commit current",
    "artifact cached",
    "dependencies resolved",
    "checksums verified",
    "manifest loaded",
    "graph locked",
    "tests executed",
    "branch clean",
    "runner log",
    "release candidate",
    "cache restored",
    "artifact signed",
    "job trace",
    "toolchain pinned",
    "analysis complete",
    "outputs recorded",
];

pub(in crate::deterministic) const SCOPE_RESTRICTIONS: [&str; 16] = [
    "source unchanged",
    "retries disabled",
    "pipeline current",
    "candidate release",
    "lockfile unchanged",
    "cache retained",
    "job current",
    "runner online",
    "validation stage",
    "dependencies unchanged",
    "shard current",
    "inputs unchanged",
    "deployment stage",
    "rebuild disabled",
    "final gate",
    "commit pinned",
];
