# HYDRA-MSG deterministic fuzz-smoke gate plus optional coverage-guided cargo-fuzz campaigns.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..\..")
Set-Location $RepoRoot

if (-not $env:HYDRA_FUZZ_CASES) {
    $env:HYDRA_FUZZ_CASES = "8"
}

if ($env:HYDRA_CI_EPHEMERAL_LOCK_REFRESH -eq "1") {
    cargo run -p hydra-fuzz-gate --
} else {
    cargo run --locked -p hydra-fuzz-gate --
}
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

if ($env:HYDRA_RUN_COVERAGE_GUIDED_FUZZ -ne "1") {
    Write-Host "coverage-guided fuzz campaigns skipped; set HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1 for release evidence"
    exit 0
}

if (-not (Get-Command rustup -ErrorAction SilentlyContinue)) {
    throw "HYDRA coverage-guided fuzzing requires rustup and a nightly Rust toolchain. Install nightly with: rustup toolchain install nightly"
}

$FuzzRuns = if ($env:HYDRA_COVERAGE_FUZZ_RUNS) { $env:HYDRA_COVERAGE_FUZZ_RUNS } else { "256" }
$FuzzToolchain = if ($env:HYDRA_FUZZ_TOOLCHAIN) { $env:HYDRA_FUZZ_TOOLCHAIN } else { "nightly" }
$FuzzDir = Join-Path $RepoRoot "qa/fuzz/cargo-fuzz"
$FuzzManifest = Join-Path $FuzzDir "Cargo.toml"
$EvidenceDir = if ($env:HYDRA_COVERAGE_FUZZ_EVIDENCE_DIR) { $env:HYDRA_COVERAGE_FUZZ_EVIDENCE_DIR } else { "target/hydra-fuzz-evidence" }
$EvidenceRoot = if ([System.IO.Path]::IsPathRooted($EvidenceDir)) {
    $EvidenceDir
} else {
    Join-Path $RepoRoot $EvidenceDir
}

if (-not (Test-Path -LiteralPath $FuzzManifest -PathType Leaf)) {
    throw "HYDRA cargo-fuzz manifest is missing: $FuzzManifest"
}

$FuzzRustcVersion = (& rustup run $FuzzToolchain rustc --version 2>&1 | Out-String).Trim()
if ($LASTEXITCODE -ne 0) {
    throw "HYDRA coverage-guided fuzzing requires the selected Rust toolchain '$FuzzToolchain'. Install it with: rustup toolchain install $FuzzToolchain`n$FuzzRustcVersion"
}
if ($FuzzRustcVersion -notmatch "nightly") {
    throw "HYDRA coverage-guided fuzzing requires nightly Rust. HYDRA_FUZZ_TOOLCHAIN=$FuzzToolchain selected: $FuzzRustcVersion"
}

$PreviousRustupToolchain = $env:RUSTUP_TOOLCHAIN
$env:RUSTUP_TOOLCHAIN = $FuzzToolchain
try {
    cargo fuzz --version | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "cargo-fuzz is required for HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1. Install it with: cargo install cargo-fuzz --locked"
    }
} finally {
    if ($null -eq $PreviousRustupToolchain) {
        Remove-Item Env:RUSTUP_TOOLCHAIN -ErrorAction SilentlyContinue
    } else {
        $env:RUSTUP_TOOLCHAIN = $PreviousRustupToolchain
    }
}

Write-Host "Coverage-guided fuzz toolchain: $FuzzToolchain ($FuzzRustcVersion)"
New-Item -ItemType Directory -Force -Path $EvidenceRoot | Out-Null

$Targets = @(
    "envelope_header_decoding",
    "protected_record_decoding",
    "message_codec",
    "storage_backup_chunk_parser",
    "contact_card_parser",
    "handshake_offer_answer_parser",
    "lobby_invite_parser",
    "anonymous_auth_token_parser",
    "fragment_reassembly",
    "session_receive_state_machine",
    "group_commit_message_parser"
)

try {
    $env:RUSTUP_TOOLCHAIN = $FuzzToolchain
    foreach ($Target in $Targets) {
        Write-Host "==> coverage-guided fuzz target: $Target runs=$FuzzRuns"
        $TargetEvidenceDir = Join-Path $EvidenceRoot $Target
        New-Item -ItemType Directory -Force -Path $TargetEvidenceDir | Out-Null
        cargo fuzz run --fuzz-dir $FuzzDir $Target -- "-runs=$FuzzRuns" "-artifact_prefix=$TargetEvidenceDir/"
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    }
} finally {
    if ($null -eq $PreviousRustupToolchain) {
        Remove-Item Env:RUSTUP_TOOLCHAIN -ErrorAction SilentlyContinue
    } else {
        $env:RUSTUP_TOOLCHAIN = $PreviousRustupToolchain
    }
}

@"
HYDRA coverage-guided fuzz evidence

Targets:
$($Targets -join "`n")

Runs per target: $FuzzRuns
Rust toolchain: $FuzzToolchain
Generated by: qa/ci/fuzz/check-fuzz.ps1
"@ | Set-Content -Path (Join-Path $EvidenceRoot "README.txt")
