#!/usr/bin/env sh
set -eu

. "$(dirname -- "$0")/../lib/repo-root.sh"
hydra_enter_repo_root

HYDRA_FUZZ_CASES="${HYDRA_FUZZ_CASES:-8}" \
  cargo run --offline -p hydra-fuzz-gate --

if [ "${HYDRA_RUN_COVERAGE_GUIDED_FUZZ:-0}" != "1" ]; then
  echo "coverage-guided fuzz campaigns skipped; set HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1 for release evidence"
  exit 0
fi

if ! command -v cargo-fuzz >/dev/null 2>&1; then
  echo "cargo-fuzz is required for HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1" >&2
  echo "Install it with: cargo install cargo-fuzz --locked" >&2
  exit 1
fi

FUZZ_RUNS="${HYDRA_COVERAGE_FUZZ_RUNS:-256}"
EVIDENCE_DIR="${HYDRA_COVERAGE_FUZZ_EVIDENCE_DIR:-target/hydra-fuzz-evidence}"
mkdir -p "$EVIDENCE_DIR"

TARGETS="
envelope_header_decoding
protected_record_decoding
message_codec
storage_backup_chunk_parser
contact_card_parser
handshake_offer_answer_parser
lobby_invite_parser
anonymous_auth_token_parser
fragment_reassembly
session_receive_state_machine
group_commit_message_parser
"

(
  cd qa/fuzz/cargo-fuzz
  for target in $TARGETS; do
    echo "==> coverage-guided fuzz target: $target runs=$FUZZ_RUNS"
    mkdir -p "../../../$EVIDENCE_DIR/$target"
    cargo fuzz run "$target" -- -runs="$FUZZ_RUNS" -artifact_prefix="../../../$EVIDENCE_DIR/$target/"
  done
)

cat > "$EVIDENCE_DIR/README.txt" <<EOF2
HYDRA coverage-guided fuzz evidence

Targets:
$TARGETS

Runs per target: $FUZZ_RUNS
Generated by: qa/ci/fuzz/check-fuzz.sh
EOF2
