# HYDRA-MSG deterministic fuzz-smoke gate plus optional coverage-guided cargo-fuzz campaigns.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..\..")
Set-Location $RepoRoot

if (-not $env:HYDRA_FUZZ_CASES) {
    $env:HYDRA_FUZZ_CASES = "8"
}

cargo run --offline -p hydra-fuzz-gate --
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

if ($env:HYDRA_RUN_COVERAGE_GUIDED_FUZZ -ne "1") {
    Write-Host "coverage-guided fuzz campaigns skipped; set HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1 for release evidence"
    exit 0
}

if (-not (Get-Command cargo-fuzz -ErrorAction SilentlyContinue)) {
    throw "cargo-fuzz is required for HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1. Install it with: cargo install cargo-fuzz --locked"
}

$FuzzRuns = if ($env:HYDRA_COVERAGE_FUZZ_RUNS) { $env:HYDRA_COVERAGE_FUZZ_RUNS } else { "256" }
$EvidenceDir = if ($env:HYDRA_COVERAGE_FUZZ_EVIDENCE_DIR) { $env:HYDRA_COVERAGE_FUZZ_EVIDENCE_DIR } else { "target/hydra-fuzz-evidence" }
New-Item -ItemType Directory -Force -Path $EvidenceDir | Out-Null

$Targets = @(
    "envelope_header_decoding",
    "protected_record_decoding",
    "message_codec",
    "storage_backup_chunk_parser",
    "contact_card_parser",
    "handshake_offer_answer_parser",
    "lobby_invite_parser",
    "anonymous_auth_token_parser",
    "fragment_reassembly",
    "session_receive_state_machine",
    "group_commit_message_parser"
)

Push-Location qa/fuzz/cargo-fuzz
try {
    foreach ($Target in $Targets) {
        Write-Host "==> coverage-guided fuzz target: $Target runs=$FuzzRuns"
        New-Item -ItemType Directory -Force -Path "../../../$EvidenceDir/$Target" | Out-Null
        cargo fuzz run $Target -- "-runs=$FuzzRuns" "-artifact_prefix=../../../$EvidenceDir/$Target/"
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    }
} finally {
    Pop-Location
}

@"
HYDRA coverage-guided fuzz evidence

Targets:
$($Targets -join "`n")

Runs per target: $FuzzRuns
Generated by: qa/ci/fuzz/check-fuzz.ps1
"@ | Set-Content -Path "$EvidenceDir/README.txt"
