#!/usr/bin/env sh
set -eu

. "$(dirname -- "$0")/../lib/repo-root.sh"
hydra_enter_repo_root

if [ "${HYDRA_CI_EPHEMERAL_LOCK_REFRESH:-0}" = "1" ]; then
  HYDRA_FUZZ_CASES="${HYDRA_FUZZ_CASES:-8}" \
    cargo run -p hydra-fuzz-gate --
else
  HYDRA_FUZZ_CASES="${HYDRA_FUZZ_CASES:-8}" \
    cargo run --locked -p hydra-fuzz-gate --
fi

if [ "${HYDRA_RUN_COVERAGE_GUIDED_FUZZ:-0}" != "1" ]; then
  echo "coverage-guided fuzz campaigns skipped; set HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1 for release evidence"
  exit 0
fi

if ! command -v rustup >/dev/null 2>&1; then
  echo "HYDRA coverage-guided fuzzing requires rustup and a nightly Rust toolchain" >&2
  echo "Install nightly with: rustup toolchain install nightly" >&2
  exit 1
fi

FUZZ_RUNS="${HYDRA_COVERAGE_FUZZ_RUNS:-256}"
FUZZ_TOOLCHAIN="${HYDRA_FUZZ_TOOLCHAIN:-nightly}"
FUZZ_DIR="$HYDRA_REPO_ROOT/qa/fuzz/cargo-fuzz"
FUZZ_MANIFEST="$FUZZ_DIR/Cargo.toml"
EVIDENCE_DIR="${HYDRA_COVERAGE_FUZZ_EVIDENCE_DIR:-target/hydra-fuzz-evidence}"
case "$EVIDENCE_DIR" in
  /*) EVIDENCE_ROOT=$EVIDENCE_DIR ;;
  *) EVIDENCE_ROOT="$HYDRA_REPO_ROOT/$EVIDENCE_DIR" ;;
esac

if [ ! -f "$FUZZ_MANIFEST" ]; then
  echo "HYDRA cargo-fuzz manifest is missing: $FUZZ_MANIFEST" >&2
  exit 1
fi

if ! fuzz_rustc_version=$(rustup run "$FUZZ_TOOLCHAIN" rustc --version 2>&1); then
  echo "HYDRA coverage-guided fuzzing requires the selected Rust toolchain: $FUZZ_TOOLCHAIN" >&2
  echo "Install it with: rustup toolchain install $FUZZ_TOOLCHAIN" >&2
  echo "$fuzz_rustc_version" >&2
  exit 1
fi
case "$fuzz_rustc_version" in
  *nightly*) ;;
  *)
    echo "HYDRA coverage-guided fuzzing requires nightly Rust" >&2
    echo "HYDRA_FUZZ_TOOLCHAIN=$FUZZ_TOOLCHAIN selected: $fuzz_rustc_version" >&2
    exit 1
    ;;
esac

if ! RUSTUP_TOOLCHAIN="$FUZZ_TOOLCHAIN" cargo fuzz --version >/dev/null 2>&1; then
  echo "cargo-fuzz is required for HYDRA_RUN_COVERAGE_GUIDED_FUZZ=1" >&2
  echo "Install it with: cargo install cargo-fuzz --locked" >&2
  exit 1
fi

echo "Coverage-guided fuzz toolchain: $FUZZ_TOOLCHAIN ($fuzz_rustc_version)"
mkdir -p "$EVIDENCE_ROOT"

TARGETS="
envelope_header_decoding
protected_record_decoding
message_codec
storage_backup_chunk_parser
contact_card_parser
handshake_offer_answer_parser
lobby_invite_parser
anonymous_auth_token_parser
fragment_reassembly
session_receive_state_machine
group_commit_message_parser
"

for target in $TARGETS; do
  echo "==> coverage-guided fuzz target: $target runs=$FUZZ_RUNS"
  target_evidence_dir="$EVIDENCE_ROOT/$target"
  mkdir -p "$target_evidence_dir"
  RUSTUP_TOOLCHAIN="$FUZZ_TOOLCHAIN" cargo fuzz run --fuzz-dir "$FUZZ_DIR" "$target" -- \
    -runs="$FUZZ_RUNS" \
    -artifact_prefix="$target_evidence_dir/"
done

cat > "$EVIDENCE_ROOT/README.txt" <<EOF2
HYDRA coverage-guided fuzz evidence

Targets:
$TARGETS

Runs per target: $FUZZ_RUNS
Rust toolchain: $FUZZ_TOOLCHAIN
Generated by: qa/ci/fuzz/check-fuzz.sh
EOF2
