$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path "$PSScriptRoot\..\..\.."
Set-Location $RepoRoot

if (-not (Get-Command wasm-pack -ErrorAction SilentlyContinue)) {
    Write-Host "wasm-pack is required. Install it with:" -ForegroundColor Yellow
    Write-Host "cargo install wasm-pack --locked" -ForegroundColor Yellow
    Write-Host "or run .\scripts\setup-dev-env.ps1" -ForegroundColor Yellow
    exit 1
}

# HYDRA's browser handshake path performs ML-KEM + ML-DSA work. Some browsers
# trap with the wasm-ld default stack during that path, so build the web package
# with an explicit stack. Apps may override this, but should not lower it without
# rerunning the browser persistence/handshake probes.
$HydraWasmStackSize = if ($env:HYDRA_WASM_STACK_SIZE) { $env:HYDRA_WASM_STACK_SIZE } else { "16777216" }
$HydraPreviousRustFlags = $env:RUSTFLAGS
$env:RUSTFLAGS = (("$HydraPreviousRustFlags -C link-arg=-zstack-size=$HydraWasmStackSize").Trim())

$OutDir = "examples/mobile_perf_web/web/pkg"
if (Test-Path $OutDir) { Remove-Item -Recurse -Force $OutDir }
wasm-pack build crates/hydra-msg-wasm --target web --release --out-dir ../../examples/mobile_perf_web/web/pkg
@"
# HYDRA mobile_perf_web generated WASM package

This directory is generated by ``examples/mobile_perf_web/scripts/build-wasm.ps1``.

It is example-local output for the mobile/browser persistence validation page. Do not edit generated files here directly; rebuild from the repo root instead.

Useful repo docs:

- [Mobile perf web example](../../README.md)
- [Main README](../../../../README.md)
- [Public developer API](../../../../docs/spec/public-developer-api.md)
- [Browser/WASM bindings](../../../../docs/impl/wasm-javascript-bindings.md)
- [Benchmark notes](../../../../docs/validation/benchmarks/benchmark-results.md)
"@ | Set-Content -Encoding UTF8 "$OutDir/README.md"
Write-Host "Built mobile benchmark example-local WASM package: examples/mobile_perf_web/web/pkg" -ForegroundColor Green
