pub fn help_text() -> &'static str {
    concat!(
        "HYDRA-MSG local app CLI\n",
        "\nUSAGE\n",
        "  hydra-app help\n",
        "  hydra-app config show\n",
        "  hydra-app config set <key> <value>\n",
        "  hydra-app identity list\n",
        "  hydra-app identity generate <label> <password>\n",
        "  hydra-app identity import-store <label> <source-path> <source-password> <new-password> [--preserve-device-id]\n",
        "  hydra-app identity import-backup <label> <backup-path> <backup-password> <identity-password> [--preserve-device-id]\n",
        "  hydra-app identity switch <identity-id>\n",
        "  hydra-app contacts list\n",
        "  hydra-app contacts my-card <identity-password>\n",
        "  hydra-app contacts add <alias> [public-key-hex]\n",
        "  hydra-app contacts review <alias> (--qr <payload> | --key <public-key-hex>)\n",
        "  hydra-app contacts trust <alias> (--qr <payload> | --key <public-key-hex>) [--accept-key-change]\n",
        "  hydra-app contacts verify-qr <alias> <qr-payload>\n",
        "  hydra-app bootstrap create <identity-password> [ttl-seconds] [recipient-fingerprint-hex]\n",
        "  hydra-app bootstrap review <join-code>\n",
        "  hydra-app chats list\n",
        "  hydra-app chats direct <trusted-contact-alias>\n",
        "  hydra-app chats group <lite|interactive|broadcast>\n",
        "  hydra-app chats send <conversation-id-hex> <identity-password> <message>\n",
        "  hydra-app chats receive-review <conversation-id-hex> <message> [sender-id-hex]\n",
        "  hydra-app backup status\n",
        "  hydra-app backup check [checkpoint-file-or-directory...]\n",
        "  hydra-app recovery export-backup <identity-password> <backup-password> <output-path> [--allow-active-device-clone]\n",
        "  hydra-app recovery inspect-backup <backup-path> <backup-password>\n",
        "  hydra-app recovery export-checkpoint <identity-password> <directory>\n",
        "  hydra-app recovery check-history [checkpoint-file-or-directory...]\n",
        "  hydra-app gui [--addr <loopback-ip:port>] [--dangerous-allow-remote]\n",
        "\nCONFIG KEYS\n",
        "  data_dir\n",
        "  direct_rekey_every_messages\n",
        "  group_lite_rekey_every_messages\n",
        "  group_interactive_rekey_every_messages\n",
        "  group_broadcast_rekey_every_messages\n",
        "  group_rekey_on_membership_change\n",
        "  rotate_identity_after_rekey_count\n",
        "  incoming_message_policy            # contacts-only | allow-unknown\n",
        "  default_group_max_members          # 2..512\n",
        "  default_chat_list_mode             # none | whitelist | blacklist\n",
        "  chat_whitelist                     # aliases/fingerprints separated by comma, semicolon, or newline\n",
        "  chat_blacklist                     # aliases/fingerprints separated by comma, semicolon, or newline\n",
        "\nPRODUCTION FLOWS\n",
        "  First run: create/import an encrypted identity, then start chats with QR/join codes.\n",
        "  Contact card: use contacts my-card to copy your own public join code for a friend.\n",
        "  Contact trust: review safety details before saving trust; key changes require explicit acceptance.\n",
        "  Storage: encrypted local identity/contact/message stores are used by both CLI and GUI.\n",
        "  GUI: local browser UI only; remote bind requires the explicit dangerous CLI flag.\n",
    )
}
